Update package.json
add missing package

  const err = new Error(message);
              ^

Error: Cannot find module 'rpc-websockets/dist/lib/client'