Update package.json
fix issue with missing module:

const err = new Error(message);
              ^

Error: Cannot find module 'rpc-websockets/dist/lib/client'